# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xzxru5ameEN6cb7V4-fFXWPsTtSMsDUs
"""

import pandas as pd
import streamlit as st

# Load the dataset
data = pd.read_csv('imdb-movies-dataset.csv')

# Check if the 'rating' column exists in the DataFrame
if 'rating' not in data.columns:
    # If not, try to find a similar column name
    possible_rating_cols = [col for col in data.columns if 'rating' in col.lower()]
    if possible_rating_cols:
        rating_col = possible_rating_cols[0]
        st.warning(f"'rating' column not found. Using '{rating_col}' instead.")
    else:
        st.error("'rating' column or a similar column not found in the dataset.")
        st.stop()  # Stop the execution of the application
else:
    rating_col = 'rating'

# Assume the 'title' column is actually 'Title' in the CSV
title_col = 'Title'  # Update with the actual column name if different

# Check if title_col exists in data.columns
if title_col not in data.columns:
    st.error(f"Error: Column '{title_col}' not found. Available columns: {data.columns}")
    st.stop()

# Application title
st.title("Fun Facts about Nicolas Cage's Filmography")

# Some interesting facts
st.write(f"Total number of films: {len(data)}")
st.write(f"Average film rating: {data[rating_col].mean():.2f}")  # Use the identified rating column
st.write("Here are some of his highest-rated films:")
st.write(data[[title_col, rating_col]].sort_values(by=rating_col, ascending=False).head(5))  # Use the identified columns
